# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(LIMIT_REQUESTS_PER_MINUTE): '12'
    env(VERSION_MIN): ''
    env(AUTHORIZATION_ENDPOINT): 'https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize'
    env(TOKEN_ENDPOINT): 'https://gw.prd.api.enedis.fr/v1/oauth2/token'
    env(TOKEN_ENDPOINT_V3): 'https://gw.ext.prod.api.enedis.fr/oauth2/v3/token'
    env(DATA_ENDPOINT): 'https://gw.ext.prod.api.enedis.fr'
    env(DISABLE_DATA_ENPOINT_AUTH): ''    
    env(PKCE): ''
    env(FLOW): ''
    env(DB_TYPE): ''
    env(DURATION): 'P3Y'
    env(MONGODB_PORT): '27017'

    env(TRUSTED_PROXIES): ''
    
    app_base_url: '%env(string:BASE_URL)%'
    app_limit_requests_per_minute : '%env(int:LIMIT_REQUESTS_PER_MINUTE)%'
    app_redirect_uri: '%env(string:REDIRECT_URI)%'
    app_authorization_endpoint: '%env(string:AUTHORIZATION_ENDPOINT)%'
    app_version_min: '%env(string:VERSION_MIN)%'
    app_token_endpoint: '%env(string:TOKEN_ENDPOINT)%'
    app_token_endpoint_v3: '%env(string:TOKEN_ENDPOINT_V3)%'
    app_data_endpoint: '%env(string:DATA_ENDPOINT)%'
    app_disable_data_enpoint_auth: '%env(defined:DISABLE_DATA_ENPOINT_AUTH)%'
    app_pkce: '%env(defined:PKCE)%'
    app_flow: '%env(string:FLOW)%'
    app_client_id: '%env(string:CLIENT_ID)%'
    app_client_secret: '%env(string:CLIENT_SECRET)%'
    app_duration: '%env(string:DURATION)%'
    app_db_address: '%env(string:DB_ADDRESS)%'
    app_db_port: '%env(string:DB_PORT)%'
    app_db_user: '%env(string:DB_USER)%'
    app_db_password: '%env(string:DB_PASSWORD)%'
    app_db_name: '%env(string:DB_NAME)%'
    app_db_type: '%env(string:DB_TYPE)%'

#    router.request_context.scheme: 'https'
#    asset.request_context.secure: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
